# We publishLocal the maven plugin instead of compile to check the maven plugin integration
# Only test sbt-bloop 1.x because of bug in `^`
matrix:
  TEST_BLOOP:
    - bin/sbt-ci.sh \
          "benchmarks/compile" \
          "jsonConfig210/test" \
          "jsonConfig211/test" \
          "jsonConfig212/test" \
          "millBloop/compile" \
          "mavenBloop/compile" \
          "gradleBloop211/compile" \
          "gradleBloop212/compile" \
          "show schemaVersion" \
          "integrationSetUpBloop" \
          "backend/test" \
          "nativeBridge/test" \
          "jsBridge06/test" \
          "jsBridge10/test" \
          "frontend/test" \
          "gradleBloop212/test" \
          "docs/makeSite"

  RUN_COMMUNITY_BUILD_EXTRA:
    - bin/sbt-ci.sh \
          "integrationSetUpBloop" \
          "frontend/testOnly bloop.tasks.IntegrationTestSuite"

  RUN_BENCHMARKS_AND_SCRIPTED:
    - bin/sbt-ci.sh \
          "sbtBloop10/scripted" \
          "benchmarks/jmh:run .*HotBloopBenchmark.* -wi 0 -i 1 -f1 -t1 -p project=with-tests -p projectName=with-tests"

  PUBLISH_ARTIFACTS:
    - bin/sbt-ci-publish.sh \
          "inspect version" \
          "set pgpPublicRing in Global := file(\"/drone/.gnupg/pubring.asc\")" \
          "set pgpSecretRing in Global := file(\"/drone/.gnupg/secring.asc\")" \
          "docs/ghpagesPushSite" \
          "releaseBloop"

  RELEASE_GITHUB_BREW:
    - bin/sbt-ci.sh \
          "frontend/updateHomebrewFormula" \
          "frontend/githubRelease"
  OS:
    - windows
    - linux
  OPS:
    - basic
    - community-build
    - extra
clone:
  git:
    image: plugins/git
    tags: true
    # We clone the submodules ourselves
    recursive: false
    depth: 50

pipeline:
  clone:
    image: plugins/git
    when:
      ref: [ refs/heads/master, refs/tags/*, refs/pull/*/head ]
      matrix:
        OS: linux
    commands:
      - ./bin/ci-clone.sh

  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - /drone/.ivy2/cache
      - /drone/.coursier
      - /drone/.sbt
      - /drone/.dodo
    volumes:
      - /cache:/cache
    cache_key: [ DRONE_REPO_OWNER, DRONE_REPO_NAME, DRONE_BRANCH ]
    when:
      ref: [ refs/heads/master, refs/tags/*, refs/pull/*/head ]
      matrix:
        OS: linux

  build:
    image: scalacenter/scala-docs:1.4
    group: build
    when:
      ref: [ refs/heads/master, refs/tags/*, refs/pull/*/head ]
      matrix:
        OS: linux
        OPS: basic
    commands:
      - export DRONE_DIR="/drone"
      - git log | head -n 20
      - . bin/set-up-dodo.sh # Source it because it exports variables
      - . bin/detect-community-build.sh # Source it because it exports variables
      - ${TEST_BLOOP}

  run_benchmarks_scripted:
    image: scalacenter/scala-docs:1.4
    group: build
    when:
      ref: [ refs/heads/master, refs/tags/*, refs/pull/*/head ]
      matrix:
        OS: linux
        OPS: extra
    commands:
      - export DRONE_DIR="/drone"
      - . bin/set-up-dodo.sh # Source it because it exports variables
      - git log | head -n 20
      - ${RUN_BENCHMARKS_AND_SCRIPTED}

  run_community_pipelined:
    image: scalacenter/scala-docs:1.4
    group: build
    when:
      ref: [ refs/heads/master, refs/tags/*, refs/pull/*/head ]
      matrix:
        OS: linux
        OPS: community-build
    commands:
      - export DRONE_DIR="/drone"
      - export PIPELINE_COMMUNITY_BUILD="true"
      - . bin/set-up-dodo.sh # Source it because it exports variables
      - git log | head -n 20
      - . bin/detect-community-build.sh # Source it because it exports variables
      - ${RUN_COMMUNITY_BUILD_EXTRA}

  build_windows:
    group: build
    image: scalacenter/scala-docs:1.4
    when:
      ref: [ refs/heads/master, refs/tags/*, refs/pull/*/head ]
      matrix:
        OS: windows
        OPS: basic
    secrets: [ bloop_jenkins_token ]
    commands:
      - ./bin/stream-jenkins-log.sh "bloop:$BLOOP_JENKINS_TOKEN"

  publish:
    image: scalacenter/scala-docs:1.4
    secrets: [ sonatype_user, sonatype_password, pgp_password, bintray_user, bintray_pass, bloopoid_private_key ]
    volumes:
      - /scalacenter:/keys
    when:
      ref: [ refs/heads/master, refs/tags/* ]
      event: [ push, tag, deployment ]
      status: success
      matrix:
        OS: linux
        OPS: basic
    commands:
      - git tag -l
      - git fetch --tags
      - git tag -l
      - git log | head -n 20
      # I have no idea why this has to be done manually... TODO: inspect why.
      - export DRONE_DIR="/drone"
      - . bin/set-up-dodo.sh # Source it because it exports variables
      - /usr/local/bin/setup_keys.sh
      - ./bin/ci-setup-bloopoid-keys.sh
      - ${PUBLISH_ARTIFACTS}

  release:
    image: scalacenter/scala-docs:1.4
    secrets: [ bloopoid_github_token ]
    volumes:
      - /scalacenter:/keys
    when:
      ref: [ refs/heads/master, refs/tags/* ]
      event: [ tag ]
      status: success
      matrix:
        OS: linux
        OPS: basic
    commands:
      - export DRONE_DIR="/drone"
      - . bin/set-up-dodo.sh # Source it because it exports variables
      - echo "oauth = $BLOOPOID_GITHUB_TOKEN" > ~/.github
      - ${RELEASE_GITHUB_BREW}

  rebuild-cache:
    image: drillster/drone-volume-cache
    when:
      ref: [ refs/heads/master, refs/tags/*, refs/pull/*/head ]
      matrix:
        OS: linux
        OPS: basic
    rebuild: true
    mount:
      - /drone/.ivy2/cache
      - /drone/.coursier
      - /drone/.sbt
      - /drone/.dodo
    volumes:
      - /cache:/cache
    cache_key: [ DRONE_REPO_OWNER, DRONE_REPO_NAME, DRONE_BRANCH ]
